#!/bin/bash

if [ -z "$1" ]
then
  echo "backup <name of current archived dir>"
  echo "  ex. backup Pon1"
  exit 85
fi

USB_DRIVE=/media/KINGSTON/H-server/
H_SERVER=/var/www/h-server/

if [ ! -d "/media/KINGSTON" ]
then
  echo "USB key not mounted! Exiting."
  exit 1
fi

DB_FILE_BACKUP=${USB_DRIVE}${1}.sql

PDF_DIR=${C_SERVER}spool/$1/
PDF_DIR_BACKUP=${USB_DRIVE}$1/

dump_database() {
  if [ ! -f "$DB_FILE_BACKUP" ]
  then
    echo "Dumping database"
    echo "$DB_FILE_BACKUP"
    mysqldump -uroot testovac > $DB_FILE_BACKUP
  else
    echo "Backup of database exists! Skipping"
  fi
}

backup_pdfs() {
  if [ -d "$PDF_DIR" ]
  then
    if [ ! -f "$PDF_DIR_BACKUP" ]
    then
      echo "Backing up PDFs ..."
      echo "$PDF_DIR"
      echo "$PDF_DIR_BACKUP"
      cp -a $PDF_DIR $PDF_DIR_BACKUP
    else
      echo "Pdf dir backup does exist! Skipping"
    fi
  else
    echo "Pdf dir does not exist! Skipping"
  fi
}

dump_database
backup_pdfs

exit 0
