#!/usr/bin/env php
<?php

if (PHP_SAPI != 'cli') die('CLI usage only');

ini_set('display_errors', FALSE);
chdir(dirname(__FILE__).'/..');
require 'config.php';

require 'src/util.php';

if (!isset($_SERVER['argv'][1])) $_SERVER['argv'][1] = null;
if ($_SERVER['argv'][1] === 'initschema') {
  require 'src/schema.php';
  initschema_cli();
}
else if ($_SERVER['argv'][1] === 'import') {
  require 'src/import.php';
  import_cli();
}
else if ($_SERVER['argv'][1] === 'droptables' && isset($_SERVER['argv'][2]) && $_SERVER['argv'][2] == '--delete-everything') {
  require 'src/schema.php';
  droptables_cli();
}
else if ($_SERVER['argv'][1] == 'givetime' && isset($_SERVER['argv'][2]) && isset($_SERVER['argv'][3])) {
  require 'src/givetime.php';
  givetime_cli();
}
else {
  print 'usage: php '.$_SERVER['argv'][0].' <action>'."\n";
  print 'actions:'."\n";
  print '  initschema'."\n";
  print '  import questions.xml'."\n";
  print '  droptables --delete-everything'."\n";
  print '  givetime <pid> <extra minutes>'."\n";
}
