#!/usr/bin/env php
<?php

if (PHP_SAPI != 'cli') die('CLI usage only');

ini_set('display_errors', FALSE);
chdir(dirname(__FILE__).'/..');
require 'config.php';

require 'src/util.php';

if (!isset($_SERVER['argv'][1])) $_SERVER['argv'][1] = null;
if ($_SERVER['argv'][1] === 'initschema') {
  require 'src/schema.php';
  initschema_cli();
}
else if ($_SERVER['argv'][1] === 'import') {
  require 'src/import.php';
  import_cli();
}
else if ($_SERVER['argv'][1] === 'droptables' && isset($_SERVER['argv'][2]) && $_SERVER['argv'][2] == '--delete-everything') {
  require 'src/schema.php';
  droptables_cli();
}
else if ($_SERVER['argv'][1] == 'givetime' && isset($_SERVER['argv'][2]) && isset($_SERVER['argv'][3])) {
  require 'src/givetime.php';
  givetime_cli();
}
else if ($_SERVER['argv'][1] == 'printfinished') {
  require 'src/print.php';
  printfinished_cli();
}
else if (($_SERVER['argv'][1] == 'printexam') && isset($_SERVER['argv'][2]) && $_SERVER['argv'][2] == '--large' && isset($_SERVER['argv'][3])) {
  require 'src/print.php';
  printexamlarge_cli($_SERVER['argv'][3]);
}
else if (($_SERVER['argv'][1] == 'printallexams') && isset($_SERVER['argv'][2])) {
  require 'src/print.php';
  printallexams_cli($_SERVER['argv'][2]);
}
else if ($_SERVER['argv'][1] == 'exportresults') {
  require 'src/results.php';
  exportresults_cli();
}
else if (($_SERVER['argv'][1] == 'printevaluatedexam') && isset($_SERVER['argv'][2]) && $_SERVER['argv'][2] == '--all') {
  require 'src/print.php';
  printallevaluatedexams_cli();
}
else if (($_SERVER['argv'][1] == 'printevaluatedexam') && isset($_SERVER['argv'][2])) {
  require 'src/print.php';
  printevaluatedexam_cli($_SERVER['argv'][2]);
}
else {
  print 'usage: php '.$_SERVER['argv'][0].' <action>'."\n";
  print 'actions:'."\n";
  print '  initschema'."\n";
  print '  import questions.xml'."\n";
  print '  droptables --delete-everything'."\n";
  print '  givetime <pid> <extra minutes>'."\n";
  print '  printfinished'."\n";
  print '  printexam --large <pid>'."\n";
  print '  printallexams <pid>'."\n";
  print '  printevaluatedexam <pid>'."\n";
  print '  printevaluatedexam --all'."\n";
  print '  exportresults'."\n";
}
